# Generated by Django 4.0.4 on 2022-05-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lector',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
