# Generated by Django 4.0.4 on 2022-05-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0004_alter_prestamo_lector_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lector',
            old_name='nacinoalidad',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='lector',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
