# Generated by Django 4.0.4 on 2022-05-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0005_rename_nacinoalidad_lector_nacionalidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector'},
        ),
    ]
